name: '3-pea-loadscenarii'


on:
 push:
   paths:
     - 'src/main/resources/pea/*.json' # match '*.json' files (created or updated)
     - 'src/test/resources/pea/*.json' # match '*.json' files (created or updated)


jobs:
  prepare-files:
    runs-on: ubuntu-latest
    outputs:
      matrix-modified: ${{ steps.file-changes.outputs.files }}
    steps:
      - name: Select added and changed resources to deploy
        uses: yumemi-inc/changed-files@v3
        id: file-changes
        with:
          statuses: added|modified
          format: 'json'
          patterns: |
            src/main/resources/pea/*.{json}
            src/test/resources/pea/*.{json}

  deploy-modified-files:
    if: ${{ needs.prepare-files.outputs.matrix-modified != '[]' }}
    needs: [ prepare-files ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJSON(needs.prepare-files.outputs.matrix-modified) }}
    steps:
      - name: Check Out Reference File
        uses: Bhacaz/checkout-files@v2
        with:
          files: ${{ matrix.file }}


      - name: Echo file
        run: |
          echo ${{ matrix.file }} # to test if the correct file was passed


      - name: Deploy to pea
        run: |
          echo HttpPea  ${{secrets.PEA_REST_ADDRESS}} | sed 's/./& /g' | | tr -d ' '
          curl -X POST "${{ secrets.PEA_REST_ADDRESS }}/pea/api/content/add" -F "scenarioFiles=@${{ github.workspace }}/${{ matrix.file }}"

  deploy-new-files:
    if: ${{ needs.prepare-files.outputs.matrix-added != '[]' }}
    needs: [prepare-files]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJSON(needs.prepare-files.outputs.matrix-added) }}
    steps:
      - name: Check Out Reference File
        uses: Bhacaz/checkout-files@v2
        with:
          files: ${{ matrix.file }}

      - name: Echo file
        run: |
          echo ${{ matrix.file }} # to test if the correct file was passed

      - name: Deploy to Pea
        run: |
          curl -X POST ${{ secrets.PEA_REST_ADDRESS }}/pea/api/content/add -F "scenarioFile=@${{ github.workspace }}/${{ matrix.file }}"
